name: Generar Reporte Eleva-T

on:
  repository_dispatch:
    types: [procesar_excel]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  procesar:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instalar dependencias
        run: pip install pandas openpyxl

      - name: Ejecutar script
        run: python script.py

      #  Commit del reporte
      - name: Commit y push del reporte
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"

          git add reportes/*.xlsx

          git commit -m "Nuevo reporte generado automáticamente" || echo "No hay cambios"

          git push

      - name: Eliminar archivo original
        run: |
          rm -f nuevo_formulario_eleva_t.xlsx

      # 🔹 Commit de eliminación
      - name: Commit eliminación del archivo original
        run: |
          git add -u

          git commit -m "Eliminar archivo original procesado" || echo "No hay cambios"

          git push
